version: 2.1

jobs:
  build:
    docker:
      # Specify the version of the Maven Docker image to use
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo/PomProject

    steps:
      - checkout

      # List the root directory contents (for debugging)
      - run: ls -la

      # Cache Maven dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "PomProject/pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Download and cache dependencies
      - run: mvn dependency:go-offline

      # Save the cache
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "PomProject/pom.xml" }}

      # Run tests
      - run: mvn test

      # Collect test results
      - store_test_results:
          path: target/surefire-reports

      # Save build artifacts
      - store_artifacts:
          path: target
